services:
  postgres:
    image: postgres:16
    container_name: tablebooker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tablebooker
    ports:
      - "5433:5432"
    volumes:
      - tablebooker_pgdata:/var/lib/postgresql/data

volumes:
  tablebooker_pgdata:
